name: pipeline_iccc

dataset_path: data/APDDv2-10023.csv

cols_to_compare:
  - "Total aesthetic score"
  - "Theme and logic"
  - "Creativity"
  - "Layout and composition"
  - "Space and perspective"
  - "Light and shadow"
  - "Color"
  - "Details and texture"
  - "The overall"
  - "Mood"

sampling:
  n_samples: 500
  n_bins: 30
  seed: 42
  method: both
